### ISSUE TITLE
USB Mapping

### ISSUE THREAD

**Issue by crystalstorm466** [halal-beef/Latitude-7390-OpenCore-EFI#10]
Hi there,

I was looking through the Kexts and I noticed you included 3 usb mapping kexts. Do I need all 3 (USBMap.kext, UTBMap.kext, and USBToolBox.kext)?
 I'm asking as I'm trying to get my usb c 3 hub working and it sometimes work. HDMI out seems to be working. The hub usb ports works somewhat. 

I did disable Thunderbolt 3 in the bios to get hot plugging working however the usb ports some what work.

**Comment by halal-beef** [comment]
yes, u need all three, u can make ur own using the dortania guide, if u do, do not include the dummy map kext as this will hinder booting

**Comment by crystalstorm466** [comment]
Do you know if I have to map the usb ports on my usb c hub?

**Comment by halal-beef** [comment]
No, you shouldn't they should come up automatically, all you need to do is map all ports on the computer

**Comment by crystalstorm466** [comment]
Oh ok got it.
