### ISSUE TITLE
Sonoma 14.4

### ISSUE THREAD

**Issue by coolwiesau** [halal-beef/Latitude-7390-OpenCore-EFI#11]
After updating to Sonoma 14.4 the machine is not booting up Mac OS completely and restarts before The Logon Screen appears.
It seems that we need an update for 14.4.

**Comment by arjunlatiyal** [comment]
just update wifi kext 14.4 (airportitlwm 2.3.0 ) , mine working fine

**Comment by halal-beef** [comment]
Issue closed, since this has been fixed in the latest commit
