### ISSUE TITLE
Installer Crashes at 12 minute

### ISSUE THREAD

**Issue by jsmith1299** [halal-beef/Latitude-7390-OpenCore-EFI#13]
Hi,

I am using this to install on my Dell Latitude 5590. Around the 12 minute mark the installer crashes. When it tries to reboot it either throws me back into the installer or will get caught into a boot loop. If I remove my SATA SSD everything is fine again. Do you happen to know what might be causing this?

I am currently on Monterey on another SSD. The EFI doesn't seem to even get as far as the installer even after updated the kexts, so trying your EFI instead. 

Thanks

**Comment by halal-beef** [comment]
Check your SSD firmware, on my 7390 when I was on Hynix I needed to upgrade the fw to make sure mac os even detected my ssd and that it was stable.

Also this shouldn't really be an issue here considering you're not using the 7390

**Comment by leandrofriedrich** [comment]
try fastboot erase abl && fastboot erase xbl && fastboot reboot

**Comment by jsmith1299** [comment]
Thanks for the update. I'm using an Enterprise SSD which doesn't have any newer firmware. It is working fine with Monterey. I'll see if I can find something else which may be causing it.

**Comment by jsmith1299** [comment]
> try fastboot erase abl && fastboot erase xbl && fastboot reboot

Where would I do this? After it crashes and gets back into the installer?

**Comment by halal-beef** [comment]
ignore him, its stupid spam

**Comment by halal-beef** [comment]
closed to lack of activity
