### ISSUE TITLE
Installer crashes at like 65% of the initial boot

### ISSUE THREAD

**Issue by vita007cz** [halal-beef/Latitude-7390-OpenCore-EFI#15]
Im installing this EFI on the latitude 7490 which is almost exactly the same machine with olaria 14.5 image. It just displays an X and a link to support.apple.com/mac/startup. Did i do something wrong? wrong image? im sorry im new to this

**Comment by halal-beef** [comment]
Uhh you probably shouldn't use olaria here, use pure Mac os dmgs and make the installer according to dortanias guides
