### ISSUE TITLE
Sonoma 14.6.1 boot crash.

### ISSUE THREAD

**Issue by farazch1** [halal-beef/Latitude-7390-OpenCore-EFI#18]
Hi,

I have dell latitude 7390, I was using macOS 14.5 and it was working good, the i've installed the macOS update from sonoma 14.5 to 14.6.1 but after installation the system crashes and restarts on apple loading screen during boot time.

I had updated the opencore bootloader, all the kexts, and also disabled secure boot in info.plist and in my laptop's BIOS, before starting 14.6.1 installation process.

Please make a fix for it🙏🏻

**Comment by halal-beef** [comment]
give me panic logs or something

**Comment by farazch1** [comment]
Instead of using the older olarila 14.3.1.RAW file,  I downloaded newer 14.6.1.RAW file and installed it using this EFI, and it worked! Nothing to worry about now, thanks!
