### ISSUE TITLE
Not working with MacOS Sequoia

### ISSUE THREAD

**Issue by farazch1** [halal-beef/Latitude-7390-OpenCore-EFI#19]
Hi,
Please make it work with MacOS sequoia, it isn't booting up 😢😢. nor entering the Mac Recovery.

If the MacOS sequoia is working fine with this EFI at your side, then please let me know so that I can fix my system.

Thankyou,

**Comment by halal-beef** [comment]
works on sequoia, stop using olaria

**Comment by farazch1** [comment]
then from where should i download raw file?

**Comment by vita007cz** [comment]
you should follow dortania guide to create a bootable usb.

**Comment by farazch1** [comment]
Got it!  Thanks

**Comment by KABAMJ0** [comment]
Does wifi and bluetooth work on sequoia, might consider upgrading @halal-beef

**Comment by halal-beef** [comment]
yes.
