### ISSUE TITLE
Touchscreen is not working

### ISSUE THREAD

**Issue by gadget1999** [halal-beef/Latitude-7390-OpenCore-EFI#20]
Thanks for the work, was able to load macOS on my 7390 now.

However, I noticed that the touchscreen is not working. Not sure if others have the same issue?

**Comment by halal-beef** [comment]
yes, its intentionally disabled, do the usbmaps and youll be able to enable it

**Comment by gadget1999** [comment]
Just curious, what's the reason for disabling touchscreen? Is it because of some issues related to it? Thanks!

**Comment by halal-beef** [comment]
mostly stability, last time I used the touchscreen on a recent macOS version, shutting down would cause a kpanic due to the touchscreen
