### ISSUE TITLE
Great Job! Sleep Issue

### ISSUE THREAD

**Issue by adalbehrt** [halal-beef/Latitude-7390-OpenCore-EFI#5]
Hi,

I've just installed Sonoma, using your EFI! My system is similar to yours, yet, the computer wakes up after a second or two when put to sleep. I have been going through Bios settings and checked/unchecked all the usual stuff. I have also implemented the pm settings recommended by Dortania. Could this be due to the Bios version I am using? It's Bios 1.35.0 in my case. Any suggestions? Thanks!

**Comment by halal-beef** [comment]
I have also seemed to have noticed this lately, I don't know what caused it tbh

**Comment by adalbehrt** [comment]
I may have found a solution. The computer enters sleep mode as it should and stays there after I've entered following pm settings in the terminal:

sudo pmset -a ttyskeepawake 0
sudo pmset -a lidwake 0

Not sure whether both settings are needed or just one of them. The system still won't fall asleep when connected to external monitor via USB-C, but that I can live with. Again, thanks for your great job compiling the EFI!

**Comment by halal-beef** [comment]
Daamn, thank you gonna pin this one for anyone else having the same problem
