### ISSUE TITLE
Fix Resolution

### ISSUE THREAD

**Issue by coldi2k3** [halal-beef/Latitude-7390-OpenCore-EFI#7]
Hi, my 7390 came equipped with a Full-HD DIsplay

Everything works perfectly. Even Boot-Sound. Unfortunately, I have the problem that I can only select a resolution of 1366x768. However, the display supports 1920x1080. Where can I find this setting?

Edit:
I already tried to set the Resolution to 1920x1080 or "max" in OpenCore. Didnt work.

Keep up your good work - Hope you can help me.

**Comment by coldi2k3** [comment]
Big Sorry - My Bad.. I've got 2 7390.. Got the wrong one with the lower resolution Display

**Comment by coldi2k3** [comment]
Big Sorry - My Bad.. I've got 2 7390.. Got the wrong one with the lower resolution Display

**Comment by halal-beef** [comment]
That's weird, I thought all 7390s shipped with a fhd display??

**Comment by coldi2k3** [comment]
It was custom ordered wtih other Displays. Because most of the users in our company use a Dock 99% we ordered some of them with 1366x768 to reduce cost.

**Comment by halal-beef** [comment]
Ahhh okay
